{{- if .Values.customDiscovery.enabled }}
apiVersion: {{ printf "%s/%s" .Values.crds.group .Values.crds.version }}
kind: Configuration
metadata:
  name: {{ .Values.customDiscovery.name }}
spec:
  protocol: 
    name: {{ .Values.customDiscovery.protocolName }}
    discoveryDetails:
      {{- range $key, $val := .Values.customDiscovery.discoveryDetails }}
      {{ $key }}: {{ $val }}
      {{- end }}
  {{- if .Values.customDiscovery.brokerPod.image }}
  brokerPodSpec:
    containers:
    - name: {{ .Values.customDiscovery.name }}-broker
      image: {{ .Values.customDiscovery.brokerPod.image | quote }}
      {{- with .Values.customDiscovery.pullPolicy }}
      imagePullPolicy: {{ . }}
      {{- end }}
      resources:
        limits:
          {{`"{{PLACEHOLDER}}"`}} : "1"
    {{- with .Values.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if .Values.customDiscovery.brokerPod.image }}
  {{- if .Values.customDiscovery.createInstanceServices }}
  instanceServiceSpec:
    type: {{ .Values.customDiscovery.instanceService.type }}
    ports:
    - name: {{ .Values.customDiscovery.instanceService.name }}
      port: {{ .Values.customDiscovery.instanceService.port }}
      protocol: {{ .Values.customDiscovery.instanceService.protocol }}
      targetPort: {{ .Values.customDiscovery.instanceService.targetPort }}
  {{- end }}
  {{- if .Values.customDiscovery.createConfigurationService }}
  configurationServiceSpec:
    type: {{ .Values.customDiscovery.configurationService.type }}
    ports:
    - name: {{ .Values.customDiscovery.configurationService.name }}
      port: {{ .Values.customDiscovery.configurationService.port }}
      protocol: {{ .Values.customDiscovery.configurationService.protocol }}
      targetPort: {{ .Values.customDiscovery.configurationService.port }}
  {{- end }}
  {{- end }}
  {{- if .Values.customDiscovery.properties }}
  properties:
  {{- toYaml . | nindent 4 }}
  {{- else }}
  properties: {}
  {{- end }}
  capacity: {{ .Values.customDiscovery.capacity }}
{{- end }}
---
{{- if .Values.customDiscovery.discovery.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: akri-custom-discovery-discovery-daemonset
spec:
  selector:
    matchLabels:
      name: akri-custom-discovery-discovery
  template:
    metadata:
      labels:
        name: akri-custom-discovery-discovery
    spec:
      containers:
      - name: akri-custom-discovery-discovery
        image: {{ .Values.customDiscovery.discovery.image.repository | quote }}
        {{- with .Values.customDiscovery.discovery.image.pullPolicy }}
        imagePullPolicy: {{ . }}
        {{- end}}
        volumeMounts:
        - name: agent-registration
          mountPath: /var/lib/akri
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.customDiscovery.discovery.nodeSelectors }}
      nodeSelector:
      {{- toYaml .Values.customDiscovery.discovery.nodeSelectors | nindent 8 }}
      {{- end }}
      volumes:
      - name: agent-registration
        hostPath:
          path: /var/lib/akri
{{- end }}