name: "Build ZeroConf Protocol Brokers"

on:
  push:
    branches:
      - zeroconf-extensibility

jobs:
  standalone:
    name: standalone
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: docker/setup-buildx-action@v1
      - name: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.crUsername }}
          password: ${{ secrets.crPassword }}
      - name: build-push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./samples/brokers/zeroconf/Dockerfiles/standalone
          tags: ghcr.io/deislabs/akri/zeroconf-broker:v1
          push: true
